/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForDoctorsRouteImport } from './routes/for-doctors'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors.$doctorId'
import { Route as BookDoctorIdRouteImport } from './routes/book.$doctorId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDoctorsRoute = ForDoctorsRouteImport.update({
  id: '/for-doctors',
  path: '/for-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDoctorIdRoute = BookDoctorIdRouteImport.update({
  id: '/book/$doctorId',
  path: '/book/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/faq': typeof FaqRoute
  '/for-doctors': typeof ForDoctorsRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/search': typeof SearchRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/faq': typeof FaqRoute
  '/for-doctors': typeof ForDoctorsRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/search': typeof SearchRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/faq': typeof FaqRoute
  '/for-doctors': typeof ForDoctorsRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/search': typeof SearchRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/doctor'
    | '/faq'
    | '/for-doctors'
    | '/login'
    | '/patient'
    | '/search'
    | '/book/$doctorId'
    | '/doctors/$doctorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/doctor'
    | '/faq'
    | '/for-doctors'
    | '/login'
    | '/patient'
    | '/search'
    | '/book/$doctorId'
    | '/doctors/$doctorId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/doctor'
    | '/faq'
    | '/for-doctors'
    | '/login'
    | '/patient'
    | '/search'
    | '/book/$doctorId'
    | '/doctors/$doctorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DoctorRoute: typeof DoctorRoute
  FaqRoute: typeof FaqRoute
  ForDoctorsRoute: typeof ForDoctorsRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRoute
  SearchRoute: typeof SearchRoute
  BookDoctorIdRoute: typeof BookDoctorIdRoute
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-doctors': {
      id: '/for-doctors'
      path: '/for-doctors'
      fullPath: '/for-doctors'
      preLoaderRoute: typeof ForDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$doctorId': {
      id: '/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/book/$doctorId'
      preLoaderRoute: typeof BookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DoctorRoute: DoctorRoute,
  FaqRoute: FaqRoute,
  ForDoctorsRoute: ForDoctorsRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRoute,
  SearchRoute: SearchRoute,
  BookDoctorIdRoute: BookDoctorIdRoute,
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
